Ej nc news task6
EdJackson98/EJ-NC-News pull request #9
Opened 2023-08-16 08:31 UTC by EdJackson98

2023-08-16 09:14 UTC, EddTheDuck requested changes
Overall decent but needs more tests, see comments, thanks

2023-08-16 09:14 UTC, EddTheDuck commented on __tests__/app.test.js
> +          });
test suite isnt complete, need a test for a status 200, valid ID but has no comments

2023-08-16 09:14 UTC, EddTheDuck commented on __tests__/app.test.js
> +describe('/api/teams/:article_id/comments', () => {
/api/teams ?

2023-08-16 09:14 UTC, EddTheDuck commented on __tests__/app.test.js
> +            expect.arrayContaining([
This is ok I suppose however very much uneeded. You already have a forEach so why not just use your assertions in that ? eg. author: expect.any(String) etc

2023-08-17 07:56 UTC, scar1377 approved these changes
OK to merge.
One thing to consider - The function checkIDExists is working almost exactly the same as fetchArticleById. Why not make use of fetchArticleById instead of making a new one

2023-08-17 08:22 UTC, merged